# Generated by Django 3.1.6 on 2021-02-23 03:18

from django.db import migrations, models
import signature.models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimg',
            name='img',
            field=models.ImageField(upload_to=signature.models.create_path),
        ),
    ]
