# Generated by Django 3.1.6 on 2021-02-23 03:29

from django.db import migrations, models
import signature.models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_auto_20210223_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signimg',
            name='img',
        ),
        migrations.AddField(
            model_name='signimg',
            name='img1',
            field=models.ImageField(blank=True, upload_to=signature.models.create_path),
        ),
        migrations.AddField(
            model_name='signimg',
            name='img2',
            field=models.ImageField(blank=True, upload_to=signature.models.create_path),
        ),
    ]
